import SkillsContextProvider from '@/components/context/SkillsContext';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'FoldMoney Assignment',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="bg-slate-200 h-screen w-full">
				<SkillsContextProvider>{children}</SkillsContextProvider>
			</body>
		</html>
	);
}
